[email]
host = "smtp.mail.ru"
port = 465
auth = true
starttls = true
ssl = true
username = "noreply@zonezero.dev"
password = "admin"
from = "noreply@zonezero.dev"
protocol = "TLSv1.2"
debug = false

[mjml]
id = ""
public = ""
secret = ""

[sentry]
dsn = "https://1f4dfd1d687a4703b7420d99953e3734@o1138855.ingest.sentry.io/4504871269105664"
